<?php
/**
 * Main file for managing general options
 */
require_once('contentblock.controller.inc');
require_once('contentblock.helper.inc');


/**
 * Implementation of hook_entity_info()
 * Registers the content block entity type
 * 
 * @return array containing all entitiy options
 */
function contentblock_entity_info() {
  $options = array(
      'contentblock' => array(
        'label' => 'Content Block',
        'controller class' => 'ContentBlockController',
        'base table' => 'contentblock',
        'fieldable' => true,
        'translation' => array(
          'locale' => TRUE,
        ),
        'entity keys' => array(
          'id' => 'bid', 
          'bundle' => 'type',
        ), 
        'bundle keys' => array(
          'bundle' => 'type',
        ),
        'bundles' => array(),
        'view modes' => array(
          'full' => array(
            'label' => t('Full contentblock'),
            'custom settings' => TRUE,
          ),
        )
    )
  );
  
  $options['contentblock']['bundles']['headline'] = array(
    'label' => 'Headline',
    'admin' => array(
      'path' => 'admin/structure/contentblock/manage/%block_type',
      'real path' => 'admin/structure/contentblock/manage/headline',
      'bundle argument' => 4,
      'access arguments' => array('administer contentblock types'),
    ),
  );
  
  return $options;
}

/**
 * Implementation of hook_menu()
 * @return string
 */
function contentblock_menu(){
  $items['admin/structure/contentblock/manage'] = array(
    'title' => 'Content Block Admin',
    'description' => 'Manage content block structure',
    'page callback' => 'contentblock_list',
    'access arguments' => array('administer contentblocks'),
  );
  
  $items['admin/structure/contentblock/manage/add'] = array(
    'title' => 'Add contentblock type',
    'description' => 'Form to add a new contentblocktype',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contentblock_type_form'),
    'access arguments' => array('administer contentblocks'),
  );
  
  $items['admin/structure/contentblock/manage/%block_type'] = array(
    'title' => 'Edit contentblock type',
    'title callback' => 'contentblock_type_page_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',//'drupal_get_form',
    'page arguments' => array('contentblock_type_form', 4),
    'access arguments' => array('administer contentblock types'),
  );
  
  $items['admin/structure/contentblock/manage/%block_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 *  
 */
function contentblock_type_page_title($block_type) {
  return 'Edit ' . $block_type->type . ' block';
}

function block_type_load($type) {
  $types = ContentBlockHelper::getInstance()->getBlockTypes();
  return isset($types[$type]) ? $types[$type] : false;
}

function contentblock_type_form() {
  $form = array();
  
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
    '#description' => t('The human-readable name for this contentblock type'),  
  );
  
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),  
  );
  
   $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save and add fields'),
  );
  
  return $form;
}

/**
 * Submit function for the contentblock type form
 * Saves all block attributes in a database table
 */
function contentblock_type_form_submit() {
  
}

/**
 * Implementation of hook_permissions()
 * Defines standard permissions to administer and use contentblocks
 */
function contentblock_permission(){
    return array(
    'administer contentblocks' =>  array(
      'title' => t('Administer contentblock types'),
      'restrict access' => TRUE,
    ),
  );
}

function contentblock_list() {
  return ('Welcome to the administration page for your content blocks!');
}